spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_BRANCH:main}
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  tracing:
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
