package com.pms.models.dto.appointment;

public enum AppointmentType {
  ANNUAL_PHYSICAL,
  CONSULTATION,
  FOLLOW_UP,
  VACCINATION,
  EMERGENCY_VISIT,
  SICK_VISIT,
  THERAPY_SESSION,
  PRE_OPERATIVE_CHECKUP,
  POS_OPERATIVE_CHECKUP
}
