INSERT IGNORE INTO `speciality` (`description`)
VALUES ('Primary Care'),
       ('Internal Medicine'),
       ('Pediatrics'),
       ('Geriatrics'),
       ('Cardiology'),
       ('Dermatology'),
       ('Endocrinology'),
       ('Gastroenterology'),
       ('Hematology'),
       ('Oncology'),
       ('Nephrology'),
       ('Pulmonology'),
       ('Rheumatology'),
       ('Neurology'),
       ('Obstetrics & Gynecology'),
       ('Ophthalmology'),
       ('Psychiatry'),
       ('Urology');